title: You've just been MORBED
author: Ryan Kam.
email: rkam1@ebnet.org
theme: minima
description: Brag Sheet- 
wrestling team co-captain
can play multiple instruments
head of volunteers for korean school

# social links
twitter_username: ryannnkam
github_username: rKam1

show_excerpts: true 
